### ISSUE TITLE
Resume Pause only works once.

### ISSUE THREAD

**Issue by rk21forever** [shingohu/flutter_record_mp3#3]
After Pressing the pause button it pauses the recording but once resumed and again paused that doesn't work.
Please check

**Comment by shingohu** [comment]
@rk21forever  I tested the demo and couldn't reproduce the problem
You tried running the demo?Or you can tell me about your test device info?

**Comment by rk21forever** [comment]
Yes I tried that too
But It is still not working
just that state of the button is changing but over all
It is not pausing the stream
when when the pause button shows it is paused it continues to record the voice recording.
I am using it on a nexus device with flutter 1.12.13+hotfix.8

**Comment by rk21forever** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivityAndFragmentDelegate(12423): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(12423): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(12423): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(12423): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@a348762
D/FlutterActivityAndFragmentDelegate(12423): Executing Dart entrypoint: main, and sending initial route: /
D/EGL_emulation(12423): eglMakeCurrent: 0xe248db60: ver 2 0 (tinfo 0xe2524b80)
I/Choreographer(12423): Skipped 313 frames!  The application may be doing too much work on its main thread.
W/ord_mp3_exampl(12423): JNI critical lock held for 18.898ms on Thread[14,tid=12442,Runnable,Thread*=0xda458c00,peer=0x12d403c0,"Binder:12423_4"]
D/EGL_emulation(12423): eglMakeCurrent: 0xed77fbe0: ver 2 0 (tinfo 0xe2511cb0)
D/RecordMp3Plugin(12423): record = /data/user/0/com.plugin.record_mp3_example/app_flutter/record/test_0.mp3
D/RecordMp3(12423): status = START
D/RecordMp3(12423): status = PAUSE
D/RecordMp3(12423): status = RESUME




No matter how many times we click on pause resume it keeps on resume state after this

**Comment by shingohu** [comment]
@rk21forever It looks like it's running on a simulator？Can you try it on a real device

**Comment by rk21forever** [comment]
I tried on a real device same problem

**Comment by MlecznyU** [comment]
Same problem for me. 
I/System.out( 4164): record complete
D/RecordMp3Plugin( 4164): record = /data/user/0/com.applaca.dyktafon/app_flutter/record/Nagranie nr.1.mp3
D/RecordMp3( 4164): status = START
D/RecordMp3( 4164): status = PAUSE
D/RecordMp3( 4164): status = RESUME
Then I try to pause or stop recording but it is not working. Checked on debugger and methods have been called but with no results. 
Tried on real device and emulator.
After the recording resumes, the recording continues until I try to send the file to the server firebase.

**Comment by BytesZero** [comment]
@shingohu 
Android I have the same problem，
1、start=>pause =>resume=>pause =>resume=>pause =>resume=>stop
2、start error type = RECORD_HAS_USED
After the last stop, the microphone has not been released and is still in use

**Comment by BytesZero** [comment]
@shingohu @rk21forever  This problem has been found, I will mention a PR later
![image](https://user-images.githubusercontent.com/8764899/86531586-3abdbe80-bef5-11ea-84f1-c9ea360a0832.png)

**Comment by BytesZero** [comment]
@shingohu @rk21forever  I have fixed this problem, please review it on this PR, feel free to contact me. https://github.com/shingohu/flutter_record_mp3/pull/5
