### ISSUE TITLE
安卓release版本报错

### ISSUE THREAD

**Issue by criusKer** [shingohu/flutter_record_mp3#8]
debug时正常，打包后报以下错误
java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Handler com.d.a.a.a.a()' on a null object reference at com.d.a.a.d.run(MP3Recorder.java:194)

**Comment by shingohu** [comment]
1.demo release是否闪退
2.如果是集成到项目中,看这个问题好像是混淆导致的,你关掉release下的混淆再试下呢

**Comment by criusKer** [comment]
谢了，关掉混淆确实可以，之前试过混淆的配置文件没成功，没想过去关掉。看来只能先关掉了

**Comment by shingohu** [comment]
> 谢了，关掉混淆确实可以，之前试过混淆的配置文件没成功，没想过去关掉。看来只能先关掉了

不配置混淆,flutter 命令打包release会默认添加混淆规则,纯flutter感觉没必要混淆,我也都是关闭的
后面我有时间再看下混淆下的问题

**Comment by criusKer** [comment]
好的 感谢回复
